version: "3.5"
services:
  traefik:
    image: traefik:v2.5
    networks:
      - test-net
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - ./config.yaml:/etc/traefik/traefik.yml
      - ./dynamic:/etc/traefik/dynamic
      - ./certs:/etc/traefik/certs
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      labels:
        - traefik.enable=false
        #- traefik.http.services.traefik.loadbalancer.server.port=80
networks:
  test-net:
    driver: overlay

