---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rabbitmq-pv-0
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.103
    path: "/data/nfshome/rabbitmq/server-0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rabbitmq-pv-1
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.103
    path: "/data/nfshome/rabbitmq/server-1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-rabbitmq-pv-2
  namespace: default
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.56.103
    path: "/data/nfshome/rabbitmq/server-2"

